name: iOS CI

on:
  push:
    branches: [main, ci-pipeline]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  xcode-build-tests:
    name: Build and Tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 'latest'

      - name: Pre-boot Simulator
        run: |
          xcrun simctl boot "iPhone 15 Pro" || true
          sleep 30

      - name: Run Unit Tests
        run: |
          xcodebuild test -project SE491GroupProject.xcodeproj -scheme SE491GroupProject -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' -enableCodeCoverage YES -resultBundlePath TestResults

      - name: Check Code Coverage
        run: |
          COVERAGE=$(xcrun xccov view --report --json TestResults.xcresult | jq '.data[0].lines.percent' | cut -d '.' -f 1)
          echo "Code Coverage: $COVERAGE%"
          if [ "$COVERAGE" -lt 30 ]; then
            echo "Code coverage is below 30%"
            exit 1
          fi

      - name: Static Code Analysis
        run: |
          # Install SwiftLint or setup SonarQube scanner
          brew install swiftlint
          swiftlint lint --reporter json > swiftlint-report.json

      - name: Post Results to PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const coverage = fs.readFileSync('TestResults/summary.txt', 'utf8');
            const lintReport = fs.readFileSync('swiftlint-report.json', 'utf8');
            const pullRequestNumber = process.env.GITHUB_REF.split('/').pop();
            const body = `### Test Results:\n\`\`\`\n${coverage}\n\`\`\`\n### Lint Report:\n\`\`\`json\n${lintReport}\n\`\`\``;
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequestNumber,
              body: body
            });
