name: iOS CI

on:
    push:
      branches:
        - main
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
  xcode-build-tests:
    name: Build and Tests
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: 'latest'
    - name: Pre-boot Simulator
      run: |
        xcrun simctl boot "iPhone 15 Pro" || true
        sleep 30
    - name: Run Unit Tests
      run: xcodebuild test -project SE491GroupProject.xcodeproj -scheme SE491GroupProject -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' -enableCodeCoverage YES -resultBundlePath TestResults